version: '3.8'
name: pangbai-xss

services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    image: ctf-pangbai-xss:latest
    network_mode: host
    environment:
      - FLAG=flag{test_real_flag}

