version: '3.8'
name: pangbai-xss

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ctf-pangbai-xss:latest
    environment:
      - FLAG=flag{test_real_flag}
    ports:
      - '53000:3000'
